---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: gsengun/rabbitmq-ha-test:0.1.8
        name: rabbitmq-ha-test
        command: ["python3", "consumer.py"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MESSAGES_IN_A_SECOND
          value: "10"
